/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_sgqy_labeler_Extra */

#ifndef _Included_io_github_sgqy_labeler_Extra
#define _Included_io_github_sgqy_labeler_Extra
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     io_github_sgqy_labeler_Extra
 * Method:    ScanFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT jboolean JNICALL Java_io_github_sgqy_labeler_Extra_ScanFile
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
